Repository op-rs/kona, pull requests merged in 2024-12, with the labels that each got.

#859 feat(workspace): Bump MSRV
  Cargo.toml
  build/asterisc/asterisc-repro.dockerfile
Labels: K-feature, A-workspace

#860 chore(ci): Distribute `linux/arm64` `kona-fpp` image
  .github/workflows/kona_fpp_docker.yaml
Labels: K-chore, A-ci

#855 chore: Bump Alloy Dependencies
  Cargo.lock
  Cargo.toml
  crates/derive/src/attributes/stateful.rs
  crates/derive/src/pipeline/core.rs
  crates/derive/src/stages/attributes_queue.rs
  crates/executor/benches/execution.rs
  crates/executor/src/executor/mod.rs
  crates/executor/src/executor/util.rs
Labels: K-chore, A-workspace, F-deps

#864 chore(deps): Update Deps
  Cargo.lock
  Cargo.toml
  bin/client/Cargo.toml
  bin/host/Cargo.toml
  crates/executor/Cargo.toml
  crates/mpt/Cargo.toml
  crates/proof-sdk/proof/Cargo.toml
Labels: K-chore, A-workspace, F-deps

#865 fix(driver): Async Payload Execution
  crates/driver/src/core.rs
  crates/driver/src/executor.rs
  crates/proof-sdk/proof/src/executor.rs
Labels: K-fix, A-driver
